apiVersion: v1
kind: Service
metadata:
  name: eda-report
  namespace: scv
  labels:
    app: eda-report
    environment: scv
spec:
  type: ClusterIP
  selector:
    app: eda-report
  ports:
    - name: metrics
      port: 5001
      targetPort: 5001
  sessionAffinity: None
