{
 "title": "Detail Stat Dashboard",
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   { "name": "endPoint" },
   { "name": "kiosk", "query": "none, kiosk" },
   { "name": "variables", "query": "none, _dash.hideVariables" },
   { "name": "timePicker", "query": "none, _dash.hideVariables" },
   { "name": "theme" }
  ]
 },
 "panels": [
  { "title": "돌아가기", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API 종합 통계",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  end_point, api_title, category_name,\n  SUM(total_count) AS total_api_calls,               -- 총 호출수\n  SUM(success_count) AS total_success,               -- 총 성공수\n  SUM(fail_count) AS total_fail,                     -- 총 실패수\n\n  CASE WHEN SUM(total_count) > 0 THEN\n    ROUND((SUM(success_count)::float / SUM(total_count))::numeric, 4)\n  ELSE 0 END AS success_rate,                        -- 성공률 (0~1)\n\n  CASE WHEN SUM(total_count) > 0 THEN\n    ROUND((SUM(fail_count)::float / SUM(total_count))::numeric, 4)\n  ELSE 0 END AS fail_rate,                           -- 실패율 (0~1)\n\n  ROUND(AVG(avg_duration_ms)::numeric, 2) AS avg_response_time_ms,           -- 평균 응답시간\n  MAX(max_duration_ms) AS max_response_time_ms,                             -- 최대 응답시간\n  MIN(min_duration_ms) AS min_response_time_ms,                             -- 최소 응답시간\n\n  ROUND(AVG(avg_response_size_bytes)::numeric, 2) AS avg_response_size_bytes,   -- 평균 응답사이즈\n  MAX(max_response_size_bytes) AS max_response_size_bytes,                      -- 최대 응답사이즈\n  MIN(min_response_size_bytes) AS min_response_size_bytes                       -- 최소 응답사이즈\n\nFROM apim.apm_api_call_stat_daily\nWHERE end_point = '${endPoint}'\nAND stat_date BETWEEN\n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\nGROUP BY end_point, api_title, category_name\nORDER BY total_api_calls DESC\n;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM(total_count), 0)         AS \"총 호출건수\",           -- total_api_calls\n  COALESCE(SUM(success_count), 0)       AS \"총 성공건수\",           -- total_success_calls\n  COALESCE(SUM(fail_count), 0)          AS \"총 실패건수\"           -- total_fail_calls\nFROM apim.apm_api_call_stat_daily\nWHERE end_point = '${endPoint}'\nAND stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\n;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM(avg_response_size_bytes * total_count), 0) AS \"전체 데이터 전송량\",  -- total_response_bytes\n  COALESCE(COUNT(DISTINCT user_id), 0)  AS \"전체 사용자수\"           -- total_user_count\nFROM apim.apm_api_call_stat_daily\nWHERE end_point = '${endPoint}'\nAND stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\n;\n"
    }
   ]
  },
  {
   "title": "최다 호출 사용자 상위",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- ① 기간 내 TOP 사용자 뽑기\nWITH top_users AS (\n  SELECT user_id, end_point\n  FROM apim.apm_api_call_stat_daily\n  WHERE end_point = '${endPoint}'\n  AND stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\n  GROUP BY end_point, user_id\n  ORDER BY SUM(total_count) DESC\n  LIMIT 5\n)\nSELECT\n  user_id,\n  SUM(total_count) AS total_api_calls   -- 호출수 합계\nFROM\n  apim.apm_api_call_stat_daily\nWHERE end_point = '${endPoint}'\nAND stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\nAND user_id IN (SELECT user_id FROM top_users)\nGROUP BY\n  end_point, user_id\nORDER BY\n  total_api_calls DESC\n;"
    }
   ]
  },
  {
   "title": "사용자 실패율 상위",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  user_id AS \"유저\",\n  CASE WHEN SUM(total_count) > 0 THEN\n    ROUND((SUM(fail_count)::float / SUM(total_count))::numeric, 2)\n  ELSE 0 END AS \"실패율\"\nFROM apim.apm_api_call_stat_daily\nWHERE end_point = '${endPoint}'\nAND stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\nGROUP BY user_id\nHAVING SUM(total_count) > 0\nORDER BY \"실패율\" DESC\nLIMIT 5\n;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(ROUND(AVG(avg_response_size_bytes)::numeric, 2), 0)  AS \"평균 응답 크기\",    -- avg_response_size_bytes\n  COALESCE(MIN(min_response_size_bytes), 0) AS \"최소 응답 크기\",                       -- min_response_size_bytes\n  COALESCE(MAX(max_response_size_bytes), 0) AS \"최대 응답 크기\"\nFROM apim.apm_api_call_stat_daily\nWHERE end_point = '${endPoint}'\nAND stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\n;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(ROUND(AVG(avg_duration_ms)::numeric, 2), 0) AS \"평균 응답 시간\",              -- avg_response_time_ms\n  COALESCE(MIN(min_duration_ms), 0)   AS \"최소 응답 시간\",                               -- min_response_time_ms\n  COALESCE(MAX(max_duration_ms), 0)   AS \"최대 응답 시간\"\nFROM apim.apm_api_call_stat_daily\nWHERE end_point = '${endPoint}'\nAND stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\n;\n"
    }
   ]
  },
  {
   "title": "주요항목 발생 요약",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "WITH daily_summary AS (\n  SELECT\n    to_char(stat_date, 'yyyy-mm-dd') AS stat_date,\n    MAX(max_duration_ms) AS max_duration,\n    MAX(max_response_size_bytes) AS max_response_size,\n    COUNT(DISTINCT user_id) AS unique_users,\n    SUM(total_count) AS total_calls,\n    SUM(fail_count) AS fail_calls\n  FROM apim.apm_api_call_stat_daily\n  WHERE end_point = '${endPoint}'\n  AND stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\n  GROUP BY stat_date\n),\n\nmax_stats AS (\n  (\n    SELECT\n      '호출 수 최다' AS 항목,\n      stat_date AS 날짜,\n      TO_CHAR(total_calls, 'FM999,999,999') || ' 건' AS 값\n    FROM daily_summary\n    ORDER BY total_calls DESC\n    LIMIT 1\n  )\n\n  UNION ALL\n\n  (\n    SELECT\n      '실패 수 최다',\n      stat_date,\n      TO_CHAR(fail_calls, 'FM999,999,999') || ' 건'\n    FROM daily_summary\n    ORDER BY fail_calls DESC\n    LIMIT 1\n  )\n\n  UNION ALL\n\n  (\n    SELECT\n      '최대 응답 시간',\n      stat_date,\n      CASE\n        WHEN max_duration >= 1000 THEN \n          TO_CHAR(ROUND(max_duration / 1000.0, 2), 'FM999,999,990.00') || ' s'\n        ELSE \n          TO_CHAR(max_duration, 'FM999,999,990') || ' ms'\n      END\n    FROM daily_summary\n    ORDER BY max_duration DESC\n    LIMIT 1\n  )\n\n  UNION ALL\n\n  (\n    SELECT\n      '최대 응답 데이터 크기',\n      stat_date,\n      CASE\n        WHEN max_response_size >= 1024 * 1024 THEN \n          TO_CHAR(ROUND(max_response_size / 1024.0 / 1024.0, 2), 'FM999,999,990.00') || ' MB'\n        WHEN max_response_size >= 1024 THEN \n          TO_CHAR(ROUND(max_response_size / 1024.0, 2), 'FM999,999,990.00') || ' KB'\n        ELSE \n          TO_CHAR(max_response_size, 'FM999,999,990') || ' bytes'\n      END\n    FROM daily_summary\n    ORDER BY max_response_size DESC\n    LIMIT 1\n  )\n\n  UNION ALL\n\n  (\n    SELECT\n      '사용자 수 최다',\n      stat_date,\n      TO_CHAR(unique_users, 'FM999,999,999') || ' 명'\n    FROM daily_summary\n    ORDER BY unique_users DESC\n    LIMIT 1\n  )\n)\n\nSELECT * FROM max_stats;\n"
    }
   ]
  },
  {
   "title": "서비스 호출 증감률 추이",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "WITH daily_calls AS (\n  SELECT\n    stat_date,\n    SUM(total_count) AS total_calls\n  FROM apim.apm_api_call_stat_daily\n  WHERE end_point = '${endPoint}'\n    AND stat_date BETWEEN \n        date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n        date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\n  GROUP BY stat_date\n),\nprev_data AS (\n  SELECT\n    a.stat_date,\n    a.total_calls,\n    (\n      SELECT b.total_calls\n      FROM daily_calls b\n      WHERE b.stat_date < a.stat_date\n      ORDER BY b.stat_date DESC\n      LIMIT 1\n    ) AS prev_total_calls\n  FROM daily_calls a\n)\nSELECT\n  stat_date AS \"time\",\n  CASE\n    WHEN prev_total_calls IS NULL THEN NULL\n    WHEN prev_total_calls = 0 AND total_calls > 0 THEN 100\n    WHEN prev_total_calls = 0 AND total_calls = 0 THEN 0\n    ELSE ROUND(((total_calls - prev_total_calls)::float / prev_total_calls)::numeric * 100, 2)\n  END AS \"증감률\"\nFROM prev_data\nORDER BY stat_date;\n"
    }
   ]
  },
  {
   "title": "서비스 응답시간 평균/최소/최대 추이",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  stat_date AS \"time\",                 -- Grafana 시계열 패널에 맞춤\n  AVG(avg_duration_ms) AS \"평균\",\n  MIN(min_duration_ms) AS \"최소\",\n  MAX(max_duration_ms) AS \"최대\"\nFROM\n  apim.apm_api_call_stat_daily\nWHERE end_point = '${endPoint}'\nAND stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\nGROUP BY\n  stat_date\nORDER BY\n  stat_date\n;"
    }
   ]
  },
  {
   "title": "서비스 호출/성공/실패 추이",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  stat_date AS \"time\",                 -- Grafana 시계열 패널에 맞춤\n  SUM(total_count) AS \"호출\",  -- 전체 호출 수\n  SUM(success_count) AS \"성공\",  -- 성공 건수\n  SUM(fail_count) AS \"실패\"         -- 실패 건수\nFROM\n  apim.apm_api_call_stat_daily\nWHERE end_point = '${endPoint}'\nAND stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\nGROUP BY\n  stat_date\nORDER BY\n  stat_date\n;"
    }
   ]
  },
  {
   "title": "서비스 응답크기 평균/최소/최대 추이",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  stat_date AS \"time\",                 -- Grafana 시계열 패널에 맞춤\n  AVG(avg_response_size_bytes) AS \"평균\",\n  MIN(min_response_size_bytes) AS \"최소\",\n  MAX(max_response_size_bytes) AS \"최대\"\nFROM\n  apim.apm_api_call_stat_daily\nWHERE end_point = '${endPoint}'\nAND stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\nGROUP BY\n  stat_date\nORDER BY\n  stat_date\n;"
    }
   ]
  },
  {
   "title": "서비스 성공률/실패율 추이",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  stat_date AS \"time\",             -- Grafana 시계열 패널 인식\n  CASE WHEN SUM(total_count) > 0 THEN\n    ROUND((SUM(success_count)::float / SUM(total_count))::numeric, 2)\n  ELSE 0 END AS \"성공률\",\n  CASE WHEN SUM(total_count) > 0 THEN\n    ROUND((SUM(fail_count)::float / SUM(total_count))::numeric, 2)\n  ELSE 0 END AS \"실패율\"\nFROM\n  apim.apm_api_call_stat_daily\nWHERE end_point = '${endPoint}'\nAND stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\nGROUP BY\n  stat_date\nORDER BY\n  stat_date\n;"
    }
   ]
  },
  {
   "title": "사용자별 API 종합 통계",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  end_point, api_title, user_id,\n  SUM(total_count) AS total_api_calls,               -- 총 호출수\n  SUM(success_count) AS total_success,               -- 총 성공수\n  SUM(fail_count) AS total_fail,                     -- 총 실패수\n\n  CASE WHEN SUM(total_count) > 0 THEN\n    ROUND((SUM(success_count)::float / SUM(total_count))::numeric, 4)\n  ELSE 0 END AS success_rate,                        -- 성공률 (0~1)\n\n  CASE WHEN SUM(total_count) > 0 THEN\n    ROUND((SUM(fail_count)::float / SUM(total_count))::numeric, 4)\n  ELSE 0 END AS fail_rate,                           -- 실패율 (0~1)\n\n  ROUND(AVG(avg_duration_ms)::numeric, 2) AS avg_response_time_ms,           -- 평균 응답시간\n  MAX(max_duration_ms) AS max_response_time_ms,                             -- 최대 응답시간\n  MIN(min_duration_ms) AS min_response_time_ms,                             -- 최소 응답시간\n\n  ROUND(AVG(avg_response_size_bytes)::numeric, 2) AS avg_response_size_bytes,   -- 평균 응답사이즈\n  MAX(max_response_size_bytes) AS max_response_size_bytes,                      -- 최대 응답사이즈\n  MIN(min_response_size_bytes) AS min_response_size_bytes                       -- 최소 응답사이즈\n\nFROM apim.apm_api_call_stat_daily\nWHERE end_point = '${endPoint}'\nAND stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\nGROUP BY end_point, api_title, user_id\nORDER BY total_api_calls DESC\n;"
    }
   ]
  }
 ]
}