{
 "title": "System Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"apim-server\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"apim-gateway\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"apim-auth\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"dynapi\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"scv-engine\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"cc-backend\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU 사용률",
   "type": "gauge",
   "description": "서버별 CPU 사용률",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(system_cpu_usage{instance=\"apim-server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_cpu_usage{instance=\"apim-gateway\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_cpu_usage{instance=\"apim-auth\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_cpu_usage{instance=\"dynapi\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_cpu_usage{instance=\"cc\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_cpu_usage{instance=\"SCV\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory 사용률",
   "type": "gauge",
   "description": "서버별 Memory 사용률",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(system_memory_used_bytes{instance=\"apim-server\"}[1m]) /\navg_over_time(system_memory_total_bytes{instance=\"apim-server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_memory_used_bytes{instance=\"apim-gateway\"}[1m]) /\navg_over_time(system_memory_total_bytes{instance=\"apim-gateway\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_memory_used_bytes{instance=\"apim-auth\"}[1m]) /\navg_over_time(system_memory_total_bytes{instance=\"apim-auth\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_memory_used_bytes{instance=\"dynapi\"}[1m]) /\navg_over_time(system_memory_total_bytes{instance=\"dynapi\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_memory_used_bytes{instance=\"cc\"}[1m]) /\navg_over_time(system_memory_total_bytes{instance=\"cc\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_memory_used_bytes{instance=\"SCV\"}[1m]) /\navg_over_time(system_memory_total_bytes{instance=\"SCV\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk 사용률",
   "type": "bargauge",
   "description": "서버별 Disk 사용률",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\navg_over_time(disk_free_bytes{instance=\"apim-server\"}[1m]) /\navg_over_time(disk_total_bytes{instance=\"apim-server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1 -\navg_over_time(disk_free_bytes{instance=\"apim-gateway\"}[1m]) /\navg_over_time(disk_total_bytes{instance=\"apim-gateway\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1 -\navg_over_time(disk_free_bytes{instance=\"apim-auth\"}[1m]) /\navg_over_time(disk_total_bytes{instance=\"apim-auth\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1 -\navg_over_time(disk_free_bytes{instance=\"dynapi\"}[1m]) /\navg_over_time(disk_total_bytes{instance=\"dynapi\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1 -\navg_over_time(disk_free_bytes{instance=\"cc\"}[1m]) /\navg_over_time(disk_total_bytes{instance=\"cc\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1 -\navg_over_time(disk_free_bytes{instance=\"SCV\"}[1m]) /\navg_over_time(disk_total_bytes{instance=\"SCV\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "평균 응답시간",
   "type": "timeseries",
   "description": "서버별 평균 응답 시간",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_sum[1m])) by (instance)\n/\nsum(rate(http_server_requests_seconds_count[1m])) by (instance)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "초 당 처리량 (TPS)",
   "type": "timeseries",
   "description": "서버별 초 당 처리량 (TPS)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "400 에러 응답률",
   "type": "timeseries",
   "description": "서버별 400 에러 응답률",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4..\"}[1m])) by (instance)\n/\nsum(rate(http_server_requests_seconds_count[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 에러 응답률",
   "type": "timeseries",
   "description": "서버별 500 에러 응답률",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m])) by (instance)\n/\nsum(rate(http_server_requests_seconds_count[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}