apiVersion: v1
kind: Pod
metadata:
  name: rbd-test-pod
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            echo "$(date) - Writing to test file" >> /mnt/ceph/test.txt;
            sleep 5;
          done
      volumeMounts:
        - name: ceph-rbd-volume
          mountPath: /mnt/ceph
  volumes:
    - name: ceph-rbd-volume
      persistentVolumeClaim:
        claimName: rbd-test-pvc
  restartPolicy: Never
