apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rbd-sc
