apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
    - name: volume-test
      image: nginx:stable-alpine
      volumeMounts:
        - name: volume
          mountPath: /data
      ports:
        - containerPort: 80
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: longhorn-test-pvc
