apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
