apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce # 단일 노드에서 읽기/쓰기 접근 권한
  volumeMode: Filesystem # FileSystem ,
  storageClassName: longhorn-storage-class
  resources:
    requests:
      storage: 1Gi
