apiVersion: v1
kind: Service
metadata:
  name: apim-gateway
  namespace: scv
  labels:
    app: apim-gateway
spec:
  selector:
    app: apim-gateway
  type: ClusterIP
  ports:
    - name: metrics
      port: 8888
      targetPort: 8888
