{
 "title": "Detail Log Dashboard",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "templating": {
  "list": [
   { "name": "endPoint" },
   { "name": "kiosk", "query": "none, kiosk" },
   { "name": "timePicker", "query": "none, _dash.hideTimePicker" },
   { "name": "variables", "query": "none, _dash.hideVariables" },
   { "name": "theme", "query": "dark, light" }
  ]
 },
 "panels": [
  { "title": "돌아가기", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "건" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(endPoint) (\n  count_over_time({job=\"gateway-logs\"} | json | endPoint=\"${endPoint}\" [${__range}])\n) or vector(0)"
    },
    {
     "direction": "backward",
     "expr": "sum by(endPoint) (\n  count_over_time({job=\"gateway-logs\"} | json | resultStatus=\"success\" | endPoint=\"${endPoint}\" [${__range}])\n) or vector(0)"
    },
    {
     "direction": "backward",
     "expr": "sum by(endPoint) (\n  count_over_time({job=\"gateway-logs\"} | json | resultStatus=\"fail\" | endPoint=\"${endPoint}\" [${__range}])\n) or vector(0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum (\n  sum_over_time({job=\"gateway-logs\"} | json | endPoint=\"${endPoint}\" | unwrap responseSize [${__range}])\n) or vector(0)"
    },
    {
     "direction": "backward",
     "expr": "count(\n  count by (userId) (\n    count_over_time({job=\"gateway-logs\"} | json | endPoint=\"${endPoint}\" [${__range}])\n  )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "서비스 호출 추이",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "건" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by () (count_over_time({job=\"gateway-logs\"} | json | endPoint=\"${endPoint}\" [5m]))",
     "legendFormat": "API_CALL"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg (\n  avg_over_time({job=\"gateway-logs\"} | json | endPoint=\"${endPoint}\" | unwrap responseSize [${__range}])\n) or vector(0)"
    },
    {
     "direction": "backward",
     "expr": "min (\n  min_over_time({job=\"gateway-logs\"} | json | endPoint=\"${endPoint}\" | unwrap responseSize [${__range}])\n) or vector(0)"
    },
    {
     "direction": "backward",
     "expr": "max (\n  max_over_time({job=\"gateway-logs\"} | json | endPoint=\"${endPoint}\" | unwrap responseSize [${__range}])\n) or vector(0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg (\n  avg_over_time({job=\"gateway-logs\"} | json | endPoint=\"${endPoint}\" | unwrap duration [${__range}])\n) or vector(0)"
    },
    {
     "direction": "backward",
     "expr": "min (\n  min_over_time({job=\"gateway-logs\"} | json | endPoint=\"${endPoint}\" | unwrap duration [${__range}])\n) or vector(0)"
    },
    {
     "direction": "backward",
     "expr": "max (\n  max_over_time({job=\"gateway-logs\"} | json | endPoint=\"${endPoint}\" | unwrap duration [${__range}])\n) or vector(0)"
    }
   ]
  },
  {
   "title": "최다 오류 내역 Top5",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "건" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by (resultMessage) (\n  count_over_time({job=\"gateway-logs\"} | json | resultStatus=\"fail\" | endPoint=\"${endPoint}\" [${__range}])\n))"
    }
   ]
  },
  {
   "title": "최다 호출 사용자 Top5",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "건" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by (userId) (\n  count_over_time({job=\"gateway-logs\"} | json | endPoint=\"${endPoint}\" [${__range}])\n))"
    }
   ]
  },
  {
   "title": "실패 발생 추이",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "건" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by () (count_over_time({job=\"gateway-logs\"} | json | endPoint=\"${endPoint}\" | resultStatus=\"fail\" [5m]))",
     "legendFormat": "API_CALL"
    }
   ]
  },
  {
   "title": "실시간 API 호출 현황",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"gateway-logs\"} \n| json\n| endPoint = \"${endPoint}\""
    }
   ]
  }
 ]
}