{
 "title": "Main Dashboard",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "kiosk", "query": "none,kiosk" },
   { "name": "timePicker", "query": "none, _dash.hideTimePicker" },
   { "name": "variables", "query": "none, _dash.hideVariables" },
   { "name": "theme", "query": "dark, light" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "건" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  count_over_time({job=\"gateway-logs\"} | json [${__range}])\n) or vector(0)"
    },
    {
     "expr": "sum (\n  count_over_time({job=\"gateway-logs\"} | json | resultStatus=\"success\" [${__range}])\n) or vector(0)"
    },
    {
     "expr": "sum (\n  count_over_time({job=\"gateway-logs\"} | json | resultStatus=\"fail\" [${__range}])\n) or vector(0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  sum_over_time({job=\"gateway-logs\"} | json | unwrap responseSize [${__range}])\n) or vector(0)"
    },
    {
     "expr": "count(\n  count by (userId) (\n    count_over_time({job=\"gateway-logs\"} | json [${__range}])\n  )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "최다 호출 서비스 Top5",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "건" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by (endPoint, apiTitle) (\n  count_over_time({job=\"gateway-logs\"} | json [${__range}])\n))"
    }
   ]
  },
  {
   "title": "최다 실패 서비스 Top5",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "건" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by (endPoint, apiTitle) (\n  count_over_time({job=\"gateway-logs\"} | json | resultStatus=\"fail\" [${__range}])\n))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (\n  avg_over_time({job=\"gateway-logs\"} | json | unwrap responseSize [${__range}])\n) or vector(0)"
    },
    {
     "expr": "min (\n  min_over_time({job=\"gateway-logs\"} | json | unwrap responseSize [${__range}])\n) or vector(0)"
    },
    {
     "expr": "max (\n  max_over_time({job=\"gateway-logs\"} | json | unwrap responseSize [${__range}])\n) or vector(0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (\n  avg_over_time({job=\"gateway-logs\"} | json | unwrap duration [${__range}])\n) or vector(0)"
    },
    {
     "expr": "min (\n  min_over_time({job=\"gateway-logs\"} | json | unwrap duration [${__range}])\n) or vector(0)"
    },
    {
     "expr": "max (\n  max_over_time({job=\"gateway-logs\"} | json | unwrap duration [${__range}])\n) or vector(0)"
    }
   ]
  },
  {
   "title": "서비스 호출 추이",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "건" } },
   "targets": [
    {
     "expr": "sum by () (count_over_time({job=\"gateway-logs\"} [10m]))",
     "legendFormat": "API_CALL"
    }
   ]
  },
  {
   "title": "게이트웨이 평균 응답시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_sum{instance=\"apim-gateway\"}[1m]))\n/\nsum(rate(http_server_requests_seconds_count{instance=\"apim-gateway\"}[1m]))) * 1000",
     "legendFormat": "Gateway"
    }
   ]
  },
  {
   "title": "게이트웨이 초 당 처리량 (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"apim-gateway\"}[1m]))",
     "legendFormat": "Gateway"
    }
   ]
  },
  {
   "title": "실시간 API 호출 집계",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (endPoint, apiTitle) (\n  count_over_time({job=\"gateway-logs\"} | json [${__range}])\n)"
    },
    {
     "direction": "backward",
     "expr": "sum by (endPoint, apiTitle) (\n  count_over_time({job=\"gateway-logs\"} | json | resultStatus=\"success\" [${__range}])\n)"
    },
    {
     "direction": "backward",
     "expr": "sum by (endPoint, apiTitle) (\n  count_over_time({job=\"gateway-logs\"} | json | resultStatus=\"fail\" [${__range}])\n)"
    }
   ]
  },
  {
   "title": "전체 서비스 호출 증감률 추이",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH daily_calls AS (\n  SELECT\n    stat_date,\n    SUM(total_count) AS total_calls\n  FROM apim.api_call_daily_stat\n  WHERE stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\n  GROUP BY stat_date\n),\nchanges AS (\n  SELECT\n    a.stat_date,\n    a.total_calls as api_call,\n    b.total_calls as pre_api_call,\n    CASE\n      WHEN b.total_calls IS NULL THEN NULL\n      WHEN b.total_calls = 0 AND a.total_calls > 0 THEN 100\n      WHEN b.total_calls = 0 AND a.total_calls = 0 THEN 0\n      ELSE ROUND(((a.total_calls - b.total_calls)::float / b.total_calls)::numeric * 100, 2)\n    END AS rate\n  FROM\n    daily_calls a\n  LEFT JOIN\n    daily_calls b\n    ON a.stat_date = b.stat_date + INTERVAL '1 day'\n)\nSELECT\n  stat_date as \"time\",     -- Grafana 시계열 인식\n  rate AS \"증감률\"\nFROM changes\n;"
    }
   ]
  },
  {
   "title": "전체 서비스 평균 응답시간 분포",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  stat_date AS \"time\",         -- X축: 날짜\n  avg_duration_ms\nFROM\n  apim.api_call_daily_stat\nWHERE stat_date BETWEEN \n      date_trunc('day', ($__timeFrom()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date AND \n      date_trunc('day', ($__timeTo()::timestamptz AT TIME ZONE 'Asia/Seoul') )::date\nORDER BY\n  stat_date\n;"
    }
   ]
  },
  {
   "title": "실시간 API 호출 현황",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"gateway-logs\"} \n| json"
    }
   ]
  },
  {
   "title": "CPU 사용률",
   "type": "gauge",
   "description": "서버별 CPU 사용률",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(system_cpu_usage{instance=\"apim-server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_cpu_usage{instance=\"apim-gateway\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_cpu_usage{instance=\"apim-auth\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_cpu_usage{instance=\"dynapi\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_cpu_usage{instance=\"cc\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_cpu_usage{instance=\"SCV\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory 사용률",
   "type": "gauge",
   "description": "서버별 Memory 사용률",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(system_memory_used_bytes{instance=\"apim-server\"}[1m]) /\navg_over_time(system_memory_total_bytes{instance=\"apim-server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_memory_used_bytes{instance=\"apim-gateway\"}[1m]) /\navg_over_time(system_memory_total_bytes{instance=\"apim-gateway\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_memory_used_bytes{instance=\"apim-auth\"}[1m]) /\navg_over_time(system_memory_total_bytes{instance=\"apim-auth\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_memory_used_bytes{instance=\"dynapi\"}[1m]) /\navg_over_time(system_memory_total_bytes{instance=\"dynapi\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_memory_used_bytes{instance=\"cc\"}[1m]) /\navg_over_time(system_memory_total_bytes{instance=\"cc\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(system_memory_used_bytes{instance=\"SCV\"}[1m]) /\navg_over_time(system_memory_total_bytes{instance=\"SCV\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk 사용률",
   "type": "bargauge",
   "description": "서버별 Disk 사용률",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\navg_over_time(disk_free_bytes{instance=\"apim-server\"}[1m]) /\navg_over_time(disk_total_bytes{instance=\"apim-server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1 -\navg_over_time(disk_free_bytes{instance=\"apim-gateway\"}[1m]) /\navg_over_time(disk_total_bytes{instance=\"apim-gateway\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1 -\navg_over_time(disk_free_bytes{instance=\"apim-auth\"}[1m]) /\navg_over_time(disk_total_bytes{instance=\"apim-auth\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1 -\navg_over_time(disk_free_bytes{instance=\"dynapi\"}[1m]) /\navg_over_time(disk_total_bytes{instance=\"dynapi\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1 -\navg_over_time(disk_free_bytes{instance=\"cc\"}[1m]) /\navg_over_time(disk_total_bytes{instance=\"cc\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1 -\navg_over_time(disk_free_bytes{instance=\"SCV\"}[1m]) /\navg_over_time(disk_total_bytes{instance=\"SCV\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}