apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rabbitmq
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://gitlab.192.168.59.101.nip.io/mygroup/spring-basic.git
    path: rabbitmq
    targetRevision: HEAD
    helm:
      valueFiles:
        - my-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
