apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: scv
  labels:
    app: test-app
spec:
  type: ClusterIP
  selector:
    app: test-app
  ports:
    - name: http
      port: 18080
      targetPort: 18080
      protocol: TCP
