apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx # 서비스가 이 레이블을 통해 파드를 선택
    spec:
      containers:
        - name: nginx
          image: nginxdemos/hello # "Hello World" 메시지를 보여주는 Nginx 이미지
          ports:
            - containerPort: 80
